name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:22.06.0-beta.0-cli-alpine3.16
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release  

