name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.15
      credentials:
        username: ${{secrets.docker_user_name}}
        password: ${{secrets.docker_user_pwd}}
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release  

